module ArticlesHelper
	US_STATES = 
		[
			['Alabama', 'AL'],
			['Alaska', 'AK'],
			['Arizona', 'AZ'],
			['Arkansas', 'AR'],
			['California', 'CA'],
			['Colorado', 'CO'],
			['Connecticut', 'CT'],
			['Delaware', 'DE'],
			['District of Columbia', 'DC'],
			['Florida', 'FL'],
			['Georgia', 'GA'],
			['Hawaii', 'HI'],
			['Idaho', 'ID'],
			['Illinois', 'IL'],
			['Indiana', 'IN'],
			['Iowa', 'IA'],
			['Kansas', 'KS'],
			['Kentucky', 'KY'],
			['Louisiana', 'LA'],
			['Maine', 'ME'],
			['Maryland', 'MD'],
			['Massachusetts', 'MA'],
			['Michigan', 'MI'],
			['Minnesota', 'MN'],
			['Mississippi', 'MS'],
			['Missouri', 'MO'],
			['Montana', 'MT'],
			['Nebraska', 'NE'],
			['Nevada', 'NV'],
			['New Hampshire', 'NH'],
			['New Jersey', 'NJ'],
			['New Mexico', 'NM'],
			['New York', 'NY'],
			['North Carolina', 'NC'],
			['North Dakota', 'ND'],
			['Ohio', 'OH'],
			['Oklahoma', 'OK'],
			['Oregon', 'OR'],
			['Pennsylvania', 'PA'],
			['Puerto Rico', 'PR'],
			['Rhode Island', 'RI'],
			['South Carolina', 'SC'],
			['South Dakota', 'SD'],
			['Tennessee', 'TN'],
			['Texas', 'TX'],
			['Utah', 'UT'],
			['Vermont', 'VT'],
			['Virginia', 'VA'],
			['Washington', 'WA'],
			['West Virginia', 'WV'],
			['Wisconsin', 'WI'],
			['Wyoming', 'WY']
	]

	INDUSTRY_TYPES = 
		[
			['Accounting', 'Accounting'], 
			['Airlines', 'Airlines'], 
			['Animation', 'Animation'], 
			['Architecture', 'Architecture'],
			['Arts', 'Arts'],
			['Banking', 'Banking'], 
			['Biotechnology', 'Biotechnology'], 
			['Chemicals', 'Chemicals'], 
			['Civil Engineering', 'Civil Engineering'],
			['Computer Games', 'Computer Games'],
			['Computer Hardware', 'Computer Hardware'], 
			['Computer Networking', 'Computer Networking'], 
			['Computer Software', 'Computer Software'], 
			['Construction', 'Construction'],
			['Consumer Services', 'Consumer Services'],
			['Cosmetics', 'Cosmetics'], 
			['Defense', 'Defense'], 
			['Education', 'Education'], 
			['Entertainment', 'Entertainment'],
			['Farming', 'Farming'],
			['Fishery', 'Fishery'], 
			['Food', 'Food'], 
			['Furniture', 'Furniture'], 
			['Gambling', 'Gambling'],
			['Graphic Design', 'Graphic Design'],
			['Health', 'Health'], 
			['Hospitality', 'Hospitality'], 
			['Human Resources', 'Human Resources'], 
			['Insurance', 'Insurance'],
			['International Affairs', 'International Affairs'],
			['Judiciary', 'Judiciary'], 
			['Libraries', 'Libraries'], 
			['Machinery', 'Machinery'], 
			['Military', 'Military'],
			['Museums', 'Museums'],
			['Music', 'Music'], 
			['Oil', 'Oil'], 
			['Pharmaceuticals', 'Pharmaceuticals'], 
			['Philanthropy', 'Philanthropy'],
			['Photography', 'Photography'],
			['Publishing', 'Publishing'], 
			['Ranching', 'Ranching'],
			['Real Estate', 'Real Estate'],
			['Sports', 'Sports'],
			['Textiles', 'Textiles'],
			['Tobacco', 'Tobacco'], 
			['Utilities', 'Utilities'],
			['Wine', 'Wine']

	] 
end
